<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.14">
  <POU Name="F_Scale" Id="{76bd311d-7d8e-4dcc-8617-1a719685d0d2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_Scale : INT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="F_Scale">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>