<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.14">
  <POU Name="FB_Diagnostics" Id="{494e92fd-4787-4ef8-80bd-96df9243d0af}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Diagnostics
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Diagnostics">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>